
baseURL=https://web.zuperpro.com/login   
browser=chrome
company_Name=Zuper-connect
useremail=cx@zuperconnect.com
password=Test@123
customerNumber=(+1) 318 310 4737
feToTransfer=ZuperTestAutomation
feEmail=zuperfe@mail.com
fePassword=Test@123
messgaeUserCompanyName=Reportbuildertest
messageUserEmail=connectadmin@gmail.com
messageUserPassword=Test@123
messageToSent=+18632777415
fileToAttach=\\resources\\Attachments
UAT_URL=https://uat.zuperpro.com/login
assetCategory=Zuper Test Category
assetCode=1223
new=C:\\Users\\rathinakumar.k\\OneDrive - Zuper,Inc\\Documents\\AttachmentsToUpload